#!/bin/bash

function prompt()
{
  DIR=$(basename "$PWD")

  case "$DIR" in
    $USER)
      simbolo='⌂ '
      ;;
    automatizacion-nube)
      simbolo='Α'
      ;;
    download|down|Descargas)
      simbolo='↓ '
      ;;
    direplos)
      simbolo='đ'
      ;;
    multi-ssh-config)
      simbolo='ѕ '
      ;;
    org)
      simbolo='○ '
      ;;
    html)
      simbolo='Н '
      ;;
    blog)
      simbolo='Ь '
      ;;
    rcc)
      simbolo='г '
      ;;
    bak)
      simbolo='к '
      ;;
    sugargca)
      simbolo='δ '
      ;;
    sugargca65)
      simbolo='ğ '
      ;;
    9cabce0)
      simbolo='۹ '
      ;;
    symfonyauditoria|auditoria)
      simbolo='α '
      ;;
    symfonyexternos|externos)
      simbolo='ε '
      ;;
    letras-viajeras|lviajeras|letras_viajeras)
      simbolo='Ḻ '
      ;;
    nube|nube.coop)
      simbolo='и '
      ;;
    org-bash-utils)
      simbolo='Ц '
      ;;
    pcap2dot)
      simbolo='ρ '
      ;;
    bin)
      simbolo='β '
      ;;
    ispconfig)
      simbolo='Ι'
      ;;
    plan-b)
      simbolo='в '
      ;;
    etc)
      simbolo='Є '
      ;;
    musica|mp3|Música)
      simbolo='♪ '
      ;;
    log|logs)
      simbolo='♣ '
      ;;
    "/")
      simbolo='╱ '
      ;;
    *)
      simbolo='▶ '
  esac

  echo $DIR | egrep "cct-[0-9]+" >/dev/null
  OK=$(echo $?)
  if [ $OK -eq 0 ]
  then
    simbolo='с '
  fi

  echo $simbolo
}

export PS1='\n\[\033[1;32m\]`prompt` '
